"""Baseline model training and cross-validation pipeline for driver impairment detection.

Ingests windowed feature tensors (.npz) generated by idd_ingest.py or TrainingBuffer,
extracts summary statistics across time windows (203 features = 29 base signals x 7 stats),
and trains a gradient-boosted classifier using strict GroupKFold on subject_id to eliminate
data leakage across subjects.

Outputs:
  - Subject-independent ROC-AUC, PR-AUC, Sensitivity, Specificity, and F1-Score.
  - Top feature importance rankings.
  - Trained model exportable for real-time inference.
"""
import argparse
import glob
import json
import os
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import joblib
import numpy as np
from sklearn.ensemble import HistGradientBoostingClassifier, RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    balanced_accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import GroupKFold
from sklearn.inspection import permutation_importance

try:
    from xgboost import XGBClassifier
    _HAVE_XGB = True
except ImportError:
    _HAVE_XGB = False


STAT_NAMES = ["mean", "std", "min", "max", "median", "p10", "p90"]

LABEL_SOBER_ALIASES = {"sober", "normal", "baseline", "alert", "control", "0", "false", ""}
LABEL_IMPAIRED_ALIASES = {"impaired", "intoxicated", "alcohol", "drunk", "drowsy", "1", "true", "positive"}


def compute_window_summary_features(windows_3d: np.ndarray, feature_names: List[str]) -> Tuple[np.ndarray, List[str]]:
    """Transform 3D window tensors (N, window_frames, n_features) into 2D summary statistics.

    Computes 7 statistics along the temporal axis for each feature:
      [mean, std, min, max, median, 10th percentile, 90th percentile]
    yielding N x (n_features * 7) flattened tabular features.
    """
    n_windows, window_frames, n_features = windows_3d.shape
    
    means = np.mean(windows_3d, axis=1)
    stds = np.std(windows_3d, axis=1)
    mins = np.min(windows_3d, axis=1)
    maxs = np.max(windows_3d, axis=1)
    medians = np.median(windows_3d, axis=1)
    p10s = np.percentile(windows_3d, 10, axis=1)
    p90s = np.percentile(windows_3d, 90, axis=1)

    # Concatenate statistics horizontally
    features_2d = np.hstack([means, stds, mins, maxs, medians, p10s, p90s])

    # Construct feature column names
    flat_names = []
    for stat in STAT_NAMES:
        for fname in feature_names:
            flat_names.append(f"{fname}_{stat}")

    return features_2d.astype(np.float32), flat_names


def load_dataset_from_npz(npz_paths: List[str]) -> Tuple[np.ndarray, np.ndarray, np.ndarray, List[str]]:
    """Load and concatenate training windows from multiple .npz archives."""
    all_features = []
    all_subjects = []
    all_labels = []
    feature_names = None

    for path in npz_paths:
        data = np.load(path, allow_pickle=True)
        feats = data["features"]  # (n_windows, window_frames, n_features)
        subs = data["subject_ids"]
        labs = data["labels"]

        if feature_names is None and "feature_names" in data:
            feature_names = list(data["feature_names"])

        all_features.append(feats)
        all_subjects.append(subs)
        all_labels.append(labs)

    if not all_features:
        raise ValueError("No valid .npz data files found to load.")

    X_3d = np.concatenate(all_features, axis=0)
    subjects = np.concatenate(all_subjects, axis=0)
    raw_labels = np.concatenate(all_labels, axis=0)

    if feature_names is None:
        feature_names = [f"feat_{i}" for i in range(X_3d.shape[2])]

    # Convert labels to binary integers (0 = Sober, 1 = Impaired)
    y = np.zeros(len(raw_labels), dtype=np.int32)
    for i, lbl in enumerate(raw_labels):
        clean_lbl = str(lbl).strip().lower()
        if clean_lbl in LABEL_IMPAIRED_ALIASES:
            y[i] = 1
        else:
            y[i] = 0

    return X_3d, y, subjects, feature_names


def generate_synthetic_dataset(n_subjects: int = 10, windows_per_subject: int = 24, window_frames: int = 90) -> Tuple[np.ndarray, np.ndarray, np.ndarray, List[str]]:
    """Generate realistic synthetic multi-subject benchmark data for self-testing without external datasets."""
    from pipeline.training_buffer import TrainingBuffer
    feature_names = list(TrainingBuffer.FEATURE_NAMES)
    n_features = len(feature_names)

    rng = np.random.RandomState(42)
    all_features = []
    all_subjects = []
    all_labels = []

    for s_idx in range(n_subjects):
        subject_id = f"sub_{s_idx:02d}"
        # Even subjects are Sober (0), odd subjects are Impaired (1)
        is_impaired = 1 if (s_idx % 2 == 1) else 0

        # Unique baseline physical characteristics per subject
        subject_ear_base = rng.uniform(0.26, 0.32)
        subject_blink_speed = rng.uniform(2.2, 3.2) if not is_impaired else rng.uniform(0.9, 1.6)
        subject_sway = rng.uniform(0.2, 0.6) if not is_impaired else rng.uniform(1.2, 2.4)

        for w_idx in range(windows_per_subject):
            w = np.zeros((window_frames, n_features), dtype=np.float32)

            # EAR signal (with occasional blinks)
            ear_trace = np.full(window_frames, subject_ear_base - (0.05 if is_impaired else 0.0))
            ear_trace += rng.normal(0.0, 0.015, window_frames)
            
            # Blink dynamics: insert 1-2 blinks
            blink_start = rng.randint(10, window_frames - 15)
            ear_trace[blink_start:blink_start + 4] = rng.uniform(0.05, 0.12)
            
            w[:, 0] = ear_trace  # ear_left
            w[:, 1] = ear_trace  # ear_right
            w[:, 2] = ear_trace  # ear_avg
            w[:, 3] = rng.uniform(0.08, 0.16, window_frames)  # mar
            w[:, 4] = 0.02 if not is_impaired else 0.18        # perclos

            # Upstroke opening velocity
            w[:, 15] = rng.normal(subject_blink_speed, 0.2, window_frames)
            # Postural sway
            w[:, 10] = rng.normal(0.0, subject_sway, window_frames)  # pitch
            w[:, 11] = rng.normal(0.0, subject_sway, window_frames)  # roll

            # Nystagmus / GEN
            if is_impaired and rng.rand() > 0.4:
                w[:, 17] = rng.uniform(4.0, 12.0, window_frames)  # gen_slow_phase_vel
                w[:, 26] = 1.0                                   # gen_detected

            # Smooth pursuit fragmentation
            w[:, 19] = rng.uniform(0.0, 0.08, window_frames) if not is_impaired else rng.uniform(0.22, 0.45, window_frames)

            all_features.append(w)
            all_subjects.append(subject_id)
            all_labels.append(is_impaired)

    X_3d = np.array(all_features, dtype=np.float32)
    y = np.array(all_labels, dtype=np.int32)
    subjects = np.array(all_subjects, dtype=str)

    return X_3d, y, subjects, feature_names


def train_and_evaluate(
    X: np.ndarray,
    y: np.ndarray,
    subjects: np.ndarray,
    feature_names: List[str],
    n_splits: int = 5,
    scale_pos_weight: Optional[float] = None,
    use_xgboost: bool = True,
    random_state: int = 42
) -> Dict:
    """Execute strict GroupKFold cross-validation preventing subject data leakage."""
    unique_subjects = np.unique(subjects)
    actual_splits = min(n_splits, len(unique_subjects))
    if actual_splits < 2:
        raise ValueError(f"Need at least 2 distinct subjects for GroupKFold validation, got {len(unique_subjects)}.")

    gkf = GroupKFold(n_splits=actual_splits)

    oof_preds = np.zeros(len(y), dtype=np.float32)
    oof_probs = np.zeros(len(y), dtype=np.float32)
    fold_metrics = []

    # Calculate class weight ratio if not explicitly supplied
    n_pos = int(np.sum(y == 1))
    n_neg = int(np.sum(y == 0))
    if scale_pos_weight is None:
        computed_scale = float(n_neg / max(1, n_pos))
    else:
        computed_scale = float(scale_pos_weight)

    print(f"\n--- Group-K-Fold Training (K={actual_splits}, Unique Subjects={len(unique_subjects)}) ---")
    print(f"Dataset: Total Windows={len(y)}, Sober={n_neg}, Impaired={n_pos} (scale_pos_weight={computed_scale:.2f})")

    models = []
    for fold, (train_idx, val_idx) in enumerate(gkf.split(X, y, groups=subjects)):
        X_train, y_train = X[train_idx], y[train_idx]
        X_val, y_val = X[val_idx], y[val_idx]
        val_subjects = np.unique(subjects[val_idx])

        if _HAVE_XGB and use_xgboost:
            clf = XGBClassifier(
                n_estimators=100,
                max_depth=4,
                learning_rate=0.08,
                scale_pos_weight=computed_scale,
                random_state=random_state,
                eval_metric="logloss"
            )
        else:
            clf = HistGradientBoostingClassifier(
                max_iter=100,
                max_depth=4,
                learning_rate=0.08,
                class_weight="balanced",
                random_state=random_state
            )

        clf.fit(X_train, y_train)
        models.append(clf)

        val_probs = clf.predict_proba(X_val)[:, 1]
        val_preds = (val_probs >= 0.50).astype(int)

        oof_probs[val_idx] = val_probs
        oof_preds[val_idx] = val_preds

        # Metrics for this fold
        roc = roc_auc_score(y_val, val_probs) if len(np.unique(y_val)) > 1 else 0.5
        pr_auc = average_precision_score(y_val, val_probs) if len(np.unique(y_val)) > 1 else 0.0
        sens = recall_score(y_val, val_preds, zero_division=0)
        tn, fp, fn, tp = confusion_matrix(y_val, val_preds, labels=[0, 1]).ravel()
        spec = float(tn / max(1, tn + fp))

        fold_metrics.append({
            "fold": fold + 1,
            "val_subjects": list(val_subjects),
            "roc_auc": float(roc),
            "pr_auc": float(pr_auc),
            "sensitivity": float(sens),
            "specificity": float(spec),
        })

        print(f"Fold {fold+1}: Val Subjects={list(val_subjects)} | ROC-AUC={roc:.3f}, PR-AUC={pr_auc:.3f}, Sens={sens:.3f}, Spec={spec:.3f}")

    # Aggregate Out-Of-Fold (OOF) Metrics
    overall_roc = float(roc_auc_score(y, oof_probs))
    overall_pr = float(average_precision_score(y, oof_probs))
    overall_sens = float(recall_score(y, oof_preds, zero_division=0))
    tn, fp, fn, tp = confusion_matrix(y, oof_preds, labels=[0, 1]).ravel()
    overall_spec = float(tn / max(1, tn + fp))
    overall_f1 = float(f1_score(y, oof_preds, zero_division=0))
    overall_acc = float(accuracy_score(y, oof_preds))
    overall_bal_acc = float(balanced_accuracy_score(y, oof_preds))

    # Feature Importance estimation
    top_features = []
    if _HAVE_XGB and use_xgboost and hasattr(models[0], "feature_importances_"):
        mean_importances = np.mean([m.feature_importances_ for m in models], axis=0)
        sorted_indices = np.argsort(mean_importances)[::-1]
        for idx in sorted_indices[:20]:
            top_features.append({
                "feature": feature_names[idx],
                "importance": float(mean_importances[idx])
            })
    else:
        # Permutation importance on the final fold
        perm_res = permutation_importance(models[0], X[:100], y[:100], n_repeats=3, random_state=random_state)
        sorted_indices = np.argsort(perm_res.importances_mean)[::-1]
        for idx in sorted_indices[:20]:
            top_features.append({
                "feature": feature_names[idx],
                "importance": float(perm_res.importances_mean[idx])
            })

    results = {
        "n_samples": int(len(y)),
        "n_features": int(X.shape[1]),
        "n_subjects": int(len(unique_subjects)),
        "model_type": "XGBClassifier" if (_HAVE_XGB and use_xgboost) else "HistGradientBoostingClassifier",
        "scale_pos_weight": computed_scale,
        "oof_metrics": {
            "roc_auc": overall_roc,
            "pr_auc": overall_pr,
            "sensitivity": overall_sens,
            "specificity": overall_spec,
            "f1_score": overall_f1,
            "accuracy": overall_acc,
            "balanced_accuracy": overall_bal_acc,
        },
        "fold_metrics": fold_metrics,
        "top_features": top_features,
    }

    # Retrain final model on all data for deployment
    if _HAVE_XGB and use_xgboost:
        final_model = XGBClassifier(
            n_estimators=120,
            max_depth=4,
            learning_rate=0.08,
            scale_pos_weight=computed_scale,
            random_state=random_state
        )
    else:
        final_model = HistGradientBoostingClassifier(
            max_iter=120,
            max_depth=4,
            learning_rate=0.08,
            class_weight="balanced",
            random_state=random_state
        )
    final_model.fit(X, y)

    return results, final_model


def main():
    parser = argparse.ArgumentParser(description="Train and evaluate baseline DMS impairment classifier.")
    parser.add_argument("--data-dir", default="./idd_output/", help="Directory containing .npz feature archives")
    parser.add_argument("--output-model", default="models/baseline_impairment_model.joblib", help="Output path for trained model")
    parser.add_argument("--report-path", default="models/training_report.json", help="Output path for JSON evaluation report")
    parser.add_argument("--test-synthetic", action="store_true", help="Generate synthetic multi-subject benchmark dataset to verify pipeline")
    parser.add_argument("--n-splits", type=int, default=5, help="Number of GroupKFold cross-validation splits")
    parser.add_argument("--scale-pos-weight", type=float, default=None, help="Positive class weight ratio (default auto)")
    parser.add_argument("--no-xgb", action="store_true", help="Force sklearn HistGradientBoosting over XGBoost")

    args = parser.parse_args()

    print("=== DMS Baseline Impairment Training Pipeline ===")

    if args.test_synthetic:
        print("Self-test mode: Generating synthetic multi-subject benchmark dataset...")
        X_3d, y, subjects, raw_feat_names = generate_synthetic_dataset(n_subjects=10, windows_per_subject=24, window_frames=90)
    else:
        pattern = os.path.join(args.data_dir, "*.npz")
        npz_files = glob.glob(pattern)
        if not npz_files:
            print(f"Error: No .npz files found in {args.data_dir}.")
            print("Tip: Run idd_ingest.py first, or use --test-synthetic to run the built-in self-test.")
            sys.exit(1)
        print(f"Found {len(npz_files)} feature archives. Loading...")
        X_3d, y, subjects, raw_feat_names = load_dataset_from_npz(npz_files)

    print(f"Aggregating 3D window tensors {X_3d.shape} into 2D summary statistics (7 per signal)...")
    X_2d, flat_feature_names = compute_window_summary_features(X_3d, raw_feat_names)
    print(f"Generated feature matrix: {X_2d.shape[0]} windows x {X_2d.shape[1]} summary features.")

    results, final_model = train_and_evaluate(
        X=X_2d,
        y=y,
        subjects=subjects,
        feature_names=flat_feature_names,
        n_splits=args.n_splits,
        scale_pos_weight=args.scale_pos_weight,
        use_xgboost=not args.no_xgb
    )

    # Print summary report
    print("\n========================================================")
    print("           OVERALL CROSS-VALIDATION RESULTS             ")
    print("========================================================")
    print(f"Model Type:         {results['model_type']}")
    print(f"Subjects Evaluated: {results['n_subjects']}")
    print(f"Windows Total:      {results['n_samples']}")
    print(f"ROC-AUC:            {results['oof_metrics']['roc_auc']:.4f}")
    print(f"PR-AUC:             {results['oof_metrics']['pr_auc']:.4f}")
    print(f"Sensitivity:        {results['oof_metrics']['sensitivity']*100:.2f}%")
    print(f"Specificity:        {results['oof_metrics']['specificity']*100:.2f}%")
    print(f"Balanced Accuracy:  {results['oof_metrics']['balanced_accuracy']*100:.2f}%")
    print(f"F1-Score:           {results['oof_metrics']['f1_score']:.4f}")
    print("--------------------------------------------------------")
    print("Top Discriminating Features:")
    for i, item in enumerate(results["top_features"][:10]):
        print(f"  {i+1:2d}. {item['feature']:<35} (weight={item['importance']:.4f})")
    print("========================================================")

    # Save artifacts
    out_model_path = Path(args.output_model)
    out_model_path.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump({"model": final_model, "feature_names": flat_feature_names, "results": results}, out_model_path)
    print(f"\nTrained model exported to: {out_model_path}")

    out_report_path = Path(args.report_path)
    out_report_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_report_path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)
    print(f"Validation report saved to: {out_report_path}")


if __name__ == "__main__":
    main()
